### ISSUE TITLE
Ascent Developer VM, Script and Wiki Page Updates

### ISSUE THREAD

**Issue by abhijitvk** [department-of-veterans-affairs/ascent-sample#22]
We have moved away from using SSH Key to using Personal Access Token for Ascent Config connection to GitHub. To consistently use the same technique for developers, we need few set of changes listed below:

- [x] @prashanthmds to remove SSH keys for GitHub from his VM. 
- [x] Re-import the Ascent repositories by using Personal Access Token 
- [x] Test the caching of Personal Access Token for GitHub so that developers don't have to enter it each time for GIT operations. Reference link: https://help.github.com/articles/caching-your-github-password-in-git/
- [x] If the above 3 items are successful, then remove setupsshkey-github.sh file and update Vagrantfile
- [x] Update Quick Start Guide page with all the new information https://github.com/department-of-veterans-affairs/ascent-sample/wiki/Guide-to-Create-a-Developer-Workstation-Template

@mmcgreev : FYI

**Comment by abhijitvk** [comment]
@prashanthmds : Go ahead and update the task list in the issue as it is completed with your comments.

**Comment by prashanthmds** [comment]
Updated the scripts & documentation across plaform repos to make connection to github through https instead of ssh.

Tested the caching of personal access token that authenticates the user to github & updated the developer workstation VM guide documentation with those steps

Moved the scripts pertaining to setting up the developer VM to a new repo

**Comment by abhijitvk** [comment]
Issue closed as the changes were completed and reviewed
